spring:
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  main:
    log-startup-info: false
    banner-mode: off


logging:
  level:
    ROOT: INFO